import { Assessment } from '@/types';
import Card from '@/components/ui/Card';

interface AssessmentResultProps {
  assessment: Assessment;
}

export default function AssessmentResult({ assessment }: AssessmentResultProps) {
  return (
    <Card className="p-6 space-y-6">
      <div>
        <h3 className="text-lg font-semibold text-slate-900 mb-1">Damage Assessment</h3>
        <p className="text-xs text-slate-500">Generated by ClaimPilot AI</p>
        <p className="text-xs text-amber-600 mt-1">This is a preliminary damage assessment and estimate, subject to change after inspection by a repair shop.</p>
      </div>

      <div>
        <h4 className="text-sm font-semibold text-slate-800 mb-3">Damage Classification</h4>
        <div className="overflow-hidden rounded-lg border border-slate-200">
          <table className="w-full text-sm">
            <thead className="bg-slate-50">
              <tr>
                <th className="text-left px-4 py-2 text-xs font-medium text-slate-500 uppercase">Area</th>
                <th className="text-left px-4 py-2 text-xs font-medium text-slate-500 uppercase">Severity</th>
                <th className="text-left px-4 py-2 text-xs font-medium text-slate-500 uppercase">Type</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {assessment.damageClassification.map((d, i) => (
                <tr key={i}>
                  <td className="px-4 py-2.5 text-slate-700">{d.area}</td>
                  <td className="px-4 py-2.5">
                    <span
                      className={`inline-flex px-2 py-0.5 rounded text-xs font-medium ${
                        d.severity === 'Severe'
                          ? 'bg-rose-50 text-rose-700'
                          : d.severity === 'Moderate'
                          ? 'bg-amber-50 text-amber-700'
                          : 'bg-emerald-50 text-emerald-700'
                      }`}
                    >
                      {d.severity}
                    </span>
                  </td>
                  <td className="px-4 py-2.5 text-slate-700">{d.type}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div>
        <h4 className="text-sm font-semibold text-slate-800 mb-3">Cost Breakdown</h4>
        <div className="overflow-hidden rounded-lg border border-slate-200">
          <table className="w-full text-sm">
            <thead className="bg-slate-50">
              <tr>
                <th className="text-left px-4 py-2 text-xs font-medium text-slate-500 uppercase">Item</th>
                <th className="text-right px-4 py-2 text-xs font-medium text-slate-500 uppercase">Labor</th>
                <th className="text-right px-4 py-2 text-xs font-medium text-slate-500 uppercase">Parts</th>
                <th className="text-right px-4 py-2 text-xs font-medium text-slate-500 uppercase">Subtotal</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {assessment.costBreakdown.map((item, i) => (
                <tr key={i}>
                  <td className="px-4 py-2.5 text-slate-700">{item.item}</td>
                  <td className="px-4 py-2.5 text-right text-slate-600">
                    {item.laborHours}h &times; ${item.laborRate}
                  </td>
                  <td className="px-4 py-2.5 text-right text-slate-600">
                    ${item.partsCost.toLocaleString()}
                  </td>
                  <td className="px-4 py-2.5 text-right font-medium text-slate-800">
                    ${item.subtotal.toLocaleString()}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="bg-slate-50 rounded-lg p-4 space-y-2">
        <div className="flex justify-between text-sm">
          <span className="text-slate-500">Policy Tier</span>
          <span className="text-slate-700">{assessment.policyTierAdjustment.tier}</span>
        </div>
        <div className="flex justify-between text-sm">
          <span className="text-slate-500">Coverage</span>
          <span className="text-slate-700">{assessment.policyTierAdjustment.coveragePercent}% after deductible</span>
        </div>
        <div className="flex justify-between text-sm">
          <span className="text-slate-500">Deductible</span>
          <span className="text-slate-700">${assessment.policyTierAdjustment.deductible.toLocaleString()}</span>
        </div>
        <div className="border-t border-slate-200 pt-2 mt-2 space-y-1">
          <div className="flex justify-between text-sm">
            <span className="text-slate-500">Total Estimate</span>
            <span className="font-semibold text-slate-900">${assessment.totalEstimate.toLocaleString()}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-slate-500">Covered Amount</span>
            <span className="font-semibold text-emerald-600">${assessment.coveredAmount.toLocaleString()}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-slate-500">Your Cost</span>
            <span className="font-medium text-slate-700">${assessment.outOfPocket.toLocaleString()}</span>
          </div>
        </div>
      </div>
    </Card>
  );
}
